### ISSUE TITLE
Does not compile in Visual Studio 15.3.

### ISSUE THREAD

**Issue by Kozlov-Sergey-Aleksandrovitch** [Zerbinati/SugaR#55]
1>------ Rebuild All started: Project: Sugar, Configuration: Release x64 ------
1>benchmark.cpp
1>bitbase.cpp
1>bitboard.cpp
1>book.cpp
1>endgame.cpp
1>evaluate.cpp
1>main.cpp
1>material.cpp
1>misc.cpp
1>movegen.cpp
1>movepick.cpp
1>pawns.cpp
1>position.cpp
1>psqt.cpp
1>search.cpp
1>search.cpp(29): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
1>tbprobe.cpp
1>thread.cpp
1>timeman.cpp
1>tt.cpp
1>tt.cpp(97): error C2666: 'UCI::Option::operator ==': 2 overloads have similar conversions
1>c:\galaxy\решения\galaxy-master\source\uci.h(59): note: could be 'bool UCI::Option::operator ==(const char *)'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)'
1>tt.cpp(97): note: or       'built-in C++ operator==(int, bool)'
1>tt.cpp(97): note: while trying to match the argument list '(UCI::Option, bool)'
1>polybook.cpp
1>Compiling...
1>uci.cpp
1>ucioption.cpp
1>Done building project "Sugar.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Check to be compilable in all systems after https://github.com/Zerbinati/SugaR/pull/56.
