### ISSUE TITLE
Error building master on macOS 10.13.5 and Xcode 9.3

### ISSUE THREAD

**Issue by mario-grgic** [Zerbinati/SugaR#89]
Trying to build master on macOS 10.13.5 and Xcode 9.3. 

```
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I get the following errors:

```
$ make build ARCH=x86-64-bmi2 COMP=clang

Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
kernel: 'Darwin'
os: ''
prefetch: 'yes'
popcnt: 'yes'
sse: 'yes'
pext: 'yes'

Flags:
CXX: clang++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto
LDFLAGS:  -m64 -arch x86_64 -mmacosx-version-min=10.9 -lpthread -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto

Testing config sanity. If this fails, try 'make help' ...

/usr/local/bin/make ARCH=x86-64-bmi2 COMP=clang all
make[1]: Entering directory '/Volumes/DATA/dev/SugaR/SugaR.git/source'
clang++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto   -c -o benchmark.o benchmark.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto   -c -o bitbase.o bitbase.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto   -c -o bitboard.o bitboard.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto   -c -o book.o book.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto   -c -o endgame.o endgame.cpp
clang++ -Wall -Wcast-qual -fno-exceptions -fno-rtti -std=c++11  -pedantic -Wextra -Wshadow -m64 -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -flto   -c -o evaluate.o evaluate.cpp
evaluate.cpp:1010:24: error: call to 'abs' is ambiguous
                        const double Beta = abs(Junior_Winning_Scale_Factor_Default * 2 / (MidgameLimit + Endgam...
                                            ^~~
/usr/include/stdlib.h:137:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:111:44: note:
      candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdlib.h:113:44: note:
      candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
evaluate.cpp:1010:17: error: default initialization of an object of const type 'const double'
                        const double Beta = abs(Junior_Winning_Scale_Factor_Default * 2 / (MidgameLimit + Endgam...
                                     ^
                                          = 0.0
evaluate.cpp:1080:36: note: in instantiation of member function '(anonymous
      namespace)::Evaluation<Trace::Tracing::NO_TRACE>::value' requested here
  return Evaluation<NO_TRACE>(pos).value();
                                   ^
evaluate.cpp:1010:17: error: default initialization of an object of const type 'const double'
                        const double Beta = abs(Junior_Winning_Scale_Factor_Default * 2 / (MidgameLimit + Endgam...
                                     ^
                                          = 0.0
evaluate.cpp:1094:36: note: in instantiation of member function '(anonymous
      namespace)::Evaluation<Trace::Tracing::TRACE>::value' requested here
  Value v = Evaluation<TRACE>(pos).value();
                                   ^
3 errors generated.
<builtin>: recipe for target 'evaluate.o' failed
make[1]: *** [evaluate.o] Error 1
make[1]: Leaving directory '/Volumes/DATA/dev/SugaR/SugaR.git/source'
Makefile:414: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by OhJayGee** [comment]
easy fix: include 'cmath' into evaluate.cpp

**Comment by OhJayGee** [comment]
@mario-grgic - can you confirm that SugaR is now building on OSX 10.13.5 Xcode 9.3? If so please close the issue. best regards,
OJG

**Comment by mario-grgic** [comment]
Yes, this now builds on macOS 10.13.5 and Xcode 9.3. Thank you.
